# Generated by Django 4.0.4 on 2023-04-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('budget', models.CharField(max_length=255)),
                ('revenue', models.CharField(max_length=255)),
                ('release_date', models.CharField(max_length=255)),
                ('runtime', models.CharField(max_length=255)),
                ('popularity', models.CharField(max_length=255)),
            ],
        ),
    ]
