# Generated by Django 4.0.4 on 2023-04-21 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='GenreMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.CharField(max_length=1000)),
                ('genre_name', models.CharField(max_length=1000)),
                ('movie_id', models.CharField(max_length=1000)),
                ('genre_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.genre')),
                ('movie_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.movie')),
            ],
        ),
    ]
