# Generated by Django 4.2 on 2023-04-21 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0002_genre_genremovie"),
    ]

    operations = [
        migrations.RemoveField(model_name="genremovie", name="genre_id",),
        migrations.RemoveField(model_name="genremovie", name="movie_id",),
    ]
