# Generated by Django 4.2 on 2023-04-24 01:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0004_keyword_productioncompanies_productioncountries_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="keywordmovie", name="keyword",),
        migrations.RemoveField(
            model_name="productioncompaniesmovie", name="production_company",
        ),
        migrations.RemoveField(
            model_name="productioncountriesmovie", name="production_country",
        ),
        migrations.AddField(
            model_name="keywordmovie",
            name="keyword_id",
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="keywordmovie",
            name="movie_ref2",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="keywords_ref2",
                to="movie_app.movie",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productioncompaniesmovie",
            name="movie_ref3",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_companies_ref3",
                to="movie_app.movie",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productioncompaniesmovie",
            name="production_companies_id",
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productioncountriesmovie",
            name="movie_ref4",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_countries_ref4",
                to="movie_app.movie",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productioncountriesmovie",
            name="production_countries_id",
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="keywordmovie",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="keywords",
                to="movie_app.movie",
            ),
        ),
        migrations.AlterField(
            model_name="productioncompaniesmovie",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_companies",
                to="movie_app.movie",
            ),
        ),
        migrations.AlterField(
            model_name="productioncountriesmovie",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_countries",
                to="movie_app.movie",
            ),
        ),
    ]
