# Generated by Django 4.2 on 2023-04-24 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0005_remove_keywordmovie_keyword_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="genremovie", old_name="movie_ref", new_name="movie_ref1",
        ),
    ]
