# Generated by Django 4.2 on 2023-04-24 01:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0006_rename_movie_ref_genremovie_movie_ref1"),
    ]

    operations = [
        migrations.RemoveField(model_name="keywordmovie", name="movie",),
        migrations.RemoveField(model_name="productioncompaniesmovie", name="movie",),
        migrations.RemoveField(model_name="productioncountriesmovie", name="movie",),
        migrations.AddField(
            model_name="keywordmovie",
            name="Keyword_name",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="keywords",
                to="movie_app.keyword",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productioncompaniesmovie",
            name="Production_company",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_companies",
                to="movie_app.productioncompanies",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productioncountriesmovie",
            name="Production_countries",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_countries",
                to="movie_app.productioncountries",
            ),
            preserve_default=False,
        ),
    ]
