# Generated by Django 4.2 on 2023-04-24 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0007_remove_keywordmovie_movie_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="keywordmovie", old_name="Keyword_name", new_name="keyword_name",
        ),
    ]
