# Generated by Django 4.2 on 2023-04-24 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0008_rename_keyword_name_keywordmovie_keyword_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="keywordmovie", name="keyword_name",),
        migrations.RemoveField(model_name="keywordmovie", name="movie_ref2",),
        migrations.RemoveField(
            model_name="productioncompaniesmovie", name="Production_company",
        ),
        migrations.RemoveField(
            model_name="productioncompaniesmovie", name="movie_ref3",
        ),
        migrations.RemoveField(
            model_name="productioncountriesmovie", name="Production_countries",
        ),
        migrations.RemoveField(
            model_name="productioncountriesmovie", name="movie_ref4",
        ),
        migrations.DeleteModel(name="Keyword",),
        migrations.DeleteModel(name="KeywordMovie",),
        migrations.DeleteModel(name="ProductionCompanies",),
        migrations.DeleteModel(name="ProductionCompaniesMovie",),
        migrations.DeleteModel(name="ProductionCountries",),
        migrations.DeleteModel(name="ProductionCountriesMovie",),
    ]
